name: Build

#on: [push, pull_request]
on: [workflow_dispatch]

jobs:
  #build-linux-i386:
  #  runs-on: ubuntu-latest

  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Build linux-i386
  #    run: |
  #      scripts/build-ubuntu-i386.sh

  build-linux-amd64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh

  actions-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build For Android
      run: |
        scripts/actions-android.sh

    - name: Upload .apk
      uses: actions/upload-artifact@v3.1.2
      with:
        path: ./patcher/patched-aligned-debugSigned.apk

  build-windows-i386:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-i386
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug
        ./waf.bat build

  build-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -8
        ./waf.bat build

  #build-dedicated-windows-i386:
  #  runs-on: windows-2019

  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Build dedicated windows-i386
  #    run: |
  #      git submodule init && git submodule update
  #      ./waf.bat configure -T debug -d
  #      ./waf.bat build

  build-dedicated-windows-amd64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated windows-amd64
      run: |
        git submodule init && git submodule update
        ./waf.bat configure -T debug -d -8
        ./waf.bat build

  #build-dedicated-linux-i386:
  #  runs-on: ubuntu-20.04

  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Build dedicated linux-i386
  #    run: |
  #      scripts/build-ubuntu-i386.sh -d

  build-dedicated-linux-amd64:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build dedicated linux-amd64
      run: |
        scripts/build-ubuntu-amd64.sh -d
